<Project Sdk="Microsoft.NET.Sdk">
		<PropertyGroup>
				<TargetFrameworks>
						netstandard2.0;netstandard2.1;net471;net472;net48;net481;net8.0;net9.0;net10.0
				</TargetFrameworks>
				<ImplicitUsings>disable</ImplicitUsings>
				<Nullable>disable</Nullable>
				<EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
				<GenerateDocumentationFile>False</GenerateDocumentationFile>
		</PropertyGroup>

		<PropertyGroup>
				<Authors>Chizl</Authors>
				<PackageId>Chizl.EmojiLive</PackageId>
				<Company>Chizl.com</Company>
				<Copyright>© 2025 chizl.com</Copyright>
				<PackageTags>fully-qualified;emoji;library;in-console;on-desktop;core;standard;framework;no-deps</PackageTags>
				<FileVersion>6.01.17.2120</FileVersion>
				<Version>6.01.17.0</Version>
				<AssemblyVersion>5.08.0.0</AssemblyVersion>
				<PackageReadmeFile>docs\README.md</PackageReadmeFile>
				<ApplicationIcon>docs\EmojiLive.ico</ApplicationIcon>
				<PackageIcon>docs\EmojiLive.png</PackageIcon>
		</PropertyGroup>

		<ItemGroup>
		  <Compile Remove="demos\**" />
		  <EmbeddedResource Remove="demos\**" />
		  <None Remove="demos\**" />
		</ItemGroup>
		
		<ItemGroup>
				<None Include="docs\README.md" Pack="true" />
				<None Include="docs\license.md" Pack="true" />
				<None Include="docs\EmojiLive.png" Pack="True" />
				<None Include="docs\EmojiLive.ico" Pack="true" />
				<None Include="THIRD-PARTY-NOTICES.txt" Pack="true" />
		</ItemGroup>

		<ItemGroup>
		  <PackageReference Include="SkiaSharp" Version="3.119.1" PrivateAssets="none" />
		</ItemGroup>
		
		<ItemGroup>
		  <Folder Include="groups\" />
		</ItemGroup>
</Project>
